apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "chart.fullname" . }}
  labels:
    app: {{ template "chart.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels:
        app: {{ template "chart.name" . }}
        release: {{ .Release.Name }}
    spec:
      {{- if .Values.rbac.enabled }}
      serviceAccountName: {{ template "chart.fullname" . }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            {{- if .Values.rest.enabled }}
            - containerPort: {{ .Values.rest.service.internalPort }}
              name: http
            {{- end }}
            {{- if .Values.grpc.enabled }}
            - containerPort: {{ .Values.grpc.service.internalPort }}
              name: grpc
            {{- end }}
            - containerPort: {{ .Values.smtp.service.internalPort }}
              name: smtp
            - containerPort: 9100
              name: metrics
          livenessProbe:
            httpGet:
              path: /status
              port: 9100
          readinessProbe:
            httpGet:
              path: /readiness
              port: 9100
          env:
            - name: KUBEMAIL_MONGODB_URL
              value: mongodb://{{ template "chart.mongodb.fullname" . }}:{{ .Values.mongodb.port }}/kubemail
            - name: KUBEMAIL_REST_ENABLED
              value: {{ .Values.rest.enabled | quote }}
            {{- if .Values.rest.enabled }}
            - name: KUBEMAIL_REST_PORT
              value: {{ .Values.rest.service.internalPort | quote }}
            {{- end }}
            - name: KUBEMAIL_GRPC_ENABLED
              value: {{ .Values.grpc.enabled | quote }}
            {{- if .Values.grpc.enabled }}
            - name: KUBEMAIL_GRPC_PORT
              value: {{ .Values.grpc.service.internalPort | quote }}
            {{- end }}
            - name: KUBEMAIL_KUBERNETES_INCLUSTER
              value: "true"
            - name: DEBUG
              value: "*"
            {{- if .Values.watcher.emailPolicyInformer.selector }}
            - name: WATCHER_EMAILPOLICYINFORMER_SELECTOR
              value: |-
                {{ toJson .Values.watcher.emailPolicyInformer.selector }}
            {{- end }}
            {{- if .Values.watcher.podInformer.selector }}
            - name: WATCHER_PODINFORMER_SELECTOR
              value: |-
                {{ toJson .Values.watcher.podInformer.selector }}
            {{- end }}
          resources:
{{ toYaml .Values.resources | indent 12 }}
    {{- if .Values.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.nodeSelector | indent 8 }}
    {{- end }}
