elasticsearch:
  host: KUBEMAIL_ELASTICSEARCH_HOST

mongodb:
  url: KUBEMAIL_MONGODB_URL

rest:
  enabled:
    __name: KUBEMAIL_REST_ENABLED
    __format: json
  port: KUBEMAIL_REST_PORT

grpc:
  enabled:
    __name: KUBEMAIL_GRPC_ENABLED
    __format: json
  port: KUBEMAIL_GRPC_PORT

sink:
  elasticsearch:
    index: KUBEMAIL_ELASTICSEARCH_SINK_INDEX

recorder:
  elasticsearch:
    index: KUBEMAIL_ELASTICSEARCH_STATS_INDEX

policy:
  provider: kubernetes
  kubernetes:
    inCluster:
      __name: KUBEMAIL_KUBERNETES_INCLUSTER
      __format: json
    static: KUBEMAIL_KUBERNETES_POLICY

watcher:
  emailPolicyInformer:
    selector: WATCHER_EMAILPOLICYINFORMER_SELECTOR
  podInformer:
    selector: WATCHER_PODINFORMER_SELECTOR
